server.port: 9001
spring.application.name: demo-nimbus
management.tracing.sampling.probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}] %m%n"
  level:
    root: info
  config: classpath:logback-spring.xml

logbook:
  filter.enabled: true
  format.style: json
  #  strategy: body-only-if-status-at-least
  #  minimum-status: 400
  obfuscate:
    headers: Authorization,X-Secret
    parameters: access_token,password
  write:
    chunk-size: 200000
    category: org.zalando.logbook.Logbook
    level: INFO
  exclude:
    - /actuator/health
    - /api/admin/**
