server.port: 9001
spring.application.name: demo-nimbus
management.tracing.sampling.probability: 1.0

logging.pattern.level: %5p

logging.level.org.zalando.logbook: TRACE

logbook:
  filter.enabled: true
  secure-filter.enabled: true
  format.style: http
  strategy: body-only-if-status-at-least
  minimum-status: 400
  obfuscate:
    headers: Authorization,X-Secret
    parameters: access_token,password
  write:
    chunk-size: 1000
  predicate:
    include: /api/**,/actuator/**
    exclude: /actuator/health,/api/admin/**
